### ISSUE TITLE
Show Daemon state and Cluster connectivity in the UI

### ISSUE THREAD

**Issue by martialblog** [Icinga/icinga-kubernetes-web#55]
Currently there are no indicators about the daemon's health and a k8s cluster's connectivity. Maybe there should be?

When the daemon is stopped or dead, the user is not informed and might think the information shown is up-to-date.

Same goes for the k8s cluster's connectivity. When the cluster is not reachable the daemon knows about it, but the UI doesn't show that the cluster cannot be reached.

But maybe that is "out of scope" when the description says "Icinga for Kubernetes is a set of components for monitoring and visualizing Kubernetes resources". Still when I want to monitor resources, the monitoring of the thing providing the resources should maybe be in scope.

**Comment by lippserd** [comment]
I added health integration like Icinga DB does it for example w/ 4747d54.
