### ISSUE TITLE
ReplicaSet with desired 0 und current 0 is unknown

### ISSUE THREAD

**Issue by martialblog** [Icinga/icinga-kubernetes-web#58]
ReplicaSet with desired 0 und current 0 is shown as unknown. Should probably be OK

![screenshot_2024-08-01-104028](https://github.com/user-attachments/assets/74fbce8e-322c-45de-a638-d22a16287f29)

**Comment by lippserd** [comment]
The reason for this is that it is most likely a configuration error. At least I can't think of the valid use case for setting desired replicas to 0.

**Comment by martialblog** [comment]
"Scale to zero" is common scenario when using HPA

**Comment by lippserd** [comment]
@jhoxhaa Please fix.
