### ISSUE TITLE
ReplicaSet shows "within grace period" but it is in the past

### ISSUE THREAD

**Issue by martialblog** [Icinga/icinga-kubernetes-web#63]
I have a ReplicaSet for a Deployment that shows "within grace period" but it is in the past:
 
![screenshot_2024-08-01-123417](https://github.com/user-attachments/assets/5c76a72b-a789-4fd4-a5ff-2a50a77cff3b)

![screenshot_2024-08-01-123444](https://github.com/user-attachments/assets/66c88da6-2d10-4de0-bc41-dcb30e037f03)

Deployment already shows the error:

![screenshot_2024-08-01-123424](https://github.com/user-attachments/assets/3b4813f3-5919-4c3a-94bc-1c2d1f97a646)

```
root@icinga:~/k8s# date
Thu Aug  1 10:37:14 UTC 2024

| admin-apache-cd7444896 | example   | ReplicaSet example/admin-apache-cd7444896 is within grace period until 2024-08-01 09:59:02 +0000 UTC, so its state is not yet evaluated
```

**Comment by lippserd** [comment]
@jhoxhaa Please investigate.
