### ISSUE TITLE
Idea: In overview lists use the namespace as the first column

### ISSUE THREAD

**Issue by martialblog** [Icinga/icinga-kubernetes-web#64]
Just an idea, maybe the namespace column should be first, not the last. This makes is simpler to tell what object I'm looking at.

For example:

![screenshot_2024-08-01-124757](https://github.com/user-attachments/assets/42eaa8a9-7382-435c-9db6-517e294aa2be)
![screenshot_2024-08-01-124808](https://github.com/user-attachments/assets/abb02669-e27d-4331-9b19-0854f01e25bd)

My eyes have to wander quite a bit until they spot the namespace.

`kubectl` does this as well:

```
kubectl get pod -A
NAMESPACE     NAME                                     READY   STATUS      RESTARTS        AGE
dev           myapp                                    1/1     Running     0               3m17s
example       admin-apache-cd7444896-8wgsd             0/1     Pending     0               56m
example       admin-apache-cd7444896-cbk8t             0/1     Pending     0               56m
```

**Comment by lippserd** [comment]
Yes, new lists will look roughly like the following:

![localhost_icingaweb2_kubernetes_pods](https://github.com/user-attachments/assets/4a4156ee-a77e-4018-a57d-e440de177aa6)

**Comment by lippserd** [comment]
Fixed.
